# Numpy

머신러닝을 관리하기 위해 자바언어는 불편하니까 주로 파이썬을 이용해서 머신러닝
대량의 데이터를 다루기 위해서는 넘파이& 판다쓰를 다뤄야한다
 => 파이썬에서 다루는 기본 자료형보다 더 복잡한 것들을 다루기 위해 넘파이 &판다쓰라는 라이브러리를 다룬다
넘파이 - 2차원 데이터& 기본적인 인덱싱  판다쓰 - 데이터 베이스 테이블 형태의 데이터를 다룬다 & 좀 더 유연한 인덱싱 
판다쓰에서는 데이터를 그대로 읽어 올 수 있다 .  csv, txt등 (그러므로 엑셀이나 sql등으로 데이터 불러오기가 용이)

In [3]:
# numpy
# numerical python
# 고성능 수치를 위한 라이브러리
# 벡터나 행렬 연산에 편리한 기능 제공
# 모든 원소는 같은 자료형만 가능

In [4]:
import numpy as np
a = np.arange( 15 ) #range랑 비슷하다고 생각하면 됨
print( a )
a = a.reshape( 3, 5 ) #차원 변경 (행, 열, order = 'F') # C 행부터 할당이 기본값, F 열부터 할당
print( a )
print( type( a ) )
print( a.shape ) #(행, 열)출력
print( a.dtype ) # 데이터 타입 출력
print( a.ndim ) #차원 출력
print( a. size )
# print( dir ( np ) )

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
<class 'numpy.ndarray'>
(3, 5)
int32
2
15


In [5]:
b = [-1, -3, 5, 9, 12, 16, 99, 0, 8, 43] #list로 numpy 만듦 (호환됨)
print( b )
print( type( b ) )
b = np.array( b )
print( type( b ) )

t = ( 10, 20, 30, 40, 50 ) #tuple도 호환됨
print( type( t ) )
t = np.array( t )
print( type ( t ) )

s = { 10, 20, 30, 40, 50 } #set도 호환됨
print( type ( s ) )
s = np.array( s )
print( type( s ) )

[-1, -3, 5, 9, 12, 16, 99, 0, 8, 43]
<class 'list'>
<class 'numpy.ndarray'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'set'>
<class 'numpy.ndarray'>


In [6]:
print( b.shape )
print( b.ndim )
print( b.dtype )
print( b )

# print( help( np ) )
print( np.abs( b ) ) # 절대값
print( np.sqrt( np.abs( b ) ) ) # 제곱근
print( np.square( b ) ) # 제곱
print( np.isnan( b ) ) # NaN 여부
print( np.sum( b ) ) # 합계
print( np.mean( b ) ) # 평균
print( np.max( b ) )  # 최댓값
print( np.min( b ) ) # 최솟값
print( np.argmax( b ) ) #최댓값 인덱스
print( np.argmin( b ) ) #최솟값 인덱스
print( np.sort( b ) ) #정렬 오름차순
print( np.sort( b )[::-1] ) #정렬 내림차순 [ start: end : step ]
print( np.median( b ) ) #중간값 구하기

(10,)
1
int32
[-1 -3  5  9 12 16 99  0  8 43]
[ 1  3  5  9 12 16 99  0  8 43]
[1.         1.73205081 2.23606798 3.         3.46410162 4.
 9.94987437 0.         2.82842712 6.55743852]
[   1    9   25   81  144  256 9801    0   64 1849]
[False False False False False False False False False False]
188
18.8
99
-3
6
1
[-3 -1  0  5  8  9 12 16 43 99]
[99 43 16 12  9  8  5  0 -1 -3]
8.5


In [7]:
c = [ [ 1,  2, 3 ], [ 4, 5, 6 ] ]
print( type( c ) )
c = np.array( c )
print( type( c ) )
print( c )

print( np.sum( c ) )
print( np.sum( c, axis=0 ) )
print( np.sum( c, axis=1 ) )
print( np.mean( c ) )
print( np.mean( c, axis=0 ) )
print( np.mean( c, axis=1 ) )
print( np.median( c ) )
print( np.median( c, axis=0 ) )
print( np.max( c ) )
print( np.max( c, axis=1 ) )

print( np.std( c ) )
print( np.var( c ) )

<class 'list'>
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
21
[5 7 9]
[ 6 15]
3.5
[2.5 3.5 4.5]
[2. 5.]
3.5
[2.5 3.5 4.5]
6
[3 6]
1.707825127659933
2.9166666666666665


In [8]:
# element wise
d = [ 10, 20, 30, 40, 50 ]
print( d )
#print( d + 2 )              #error
d = np.array( d )
print( d + 2 )

e = np.array( [1, 2, 3, 4, 5] )

print( d + e )
print( d **  2)
print( d * np.sin( d ) )
print( d > 35 )

print( np.add( d, e ) )
print( np.subtract( d, e ) )
print( np.multiply( d, e ) )
print( np.divide( d, e ) )


[10, 20, 30, 40, 50]
[12 22 32 42 52]
[11 22 33 44 55]
[ 100  400  900 1600 2500]
[ -5.44021111  18.25890501 -29.64094872  29.80452642 -13.11874269]
[False False False  True  True]
[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]


In [9]:
f = np.array( [ [ 0, 1 ], [ 1, 1 ] ] )
g = np.array( [ [ 2, 0 ], [ 3, 4 ] ] )
print( f * g )           #그냥 곱셈
print( f @ g )           # 행렬곱
print( np.dot( f, g ) )
print( f.dot( g ) )

[[0 0]
 [3 4]]
[[3 4]
 [5 4]]
[[3 4]
 [5 4]]
[[3 4]
 [5 4]]


In [10]:
h = np.zeros( 10 )
print( h )
i = np.zeros( ( 5, 5 ) )#zeros는 튜플로 줘야함!!
print( i )
j = np.ones( 10 )
print( j )
k = np.ones( ( 5, 5 ) ) #ones도 튜플로 줘야함!
print( k )

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# 난수 생성

In [12]:
# np.random.random        0~1 사이의 난수 발생
# np.random.randint       균일 분포의 정수 난수 발생
# np.random.rand          0~1 사이의 균일 분포 난수 matrix array 생성
# np.random.randn         가우시안 표준 정규 분포 난수 matrix array 생성
# np.random.nomral        평균, 표준편차, sample 개수

# l = int(np.random.random( 10 ) * 100)     int는 데이터를 하나씩만 바꿀 수 있는데 얘는 데이터가 여러개이므로 error
l = (np.random.random( 10 ) * 100)          #여기서 10은 개수 지정임
m = l.astype(int)
n = np.array( [ int(i) for i in l ] )
print( type( l ) )
print( l )
print( m )
print( n )

print( np.random.randint( 10, 20 ) )        #여기서 (10, 20)은 범위 지정임
print( np.random.rand( 5, 2 ) )             #여기서 (5, 2)는 5행 2열

<class 'numpy.ndarray'>
[ 4.99494303 45.36897501 39.22545842 72.64222669 74.10095762 44.3930564
 30.58172422 17.54331778 60.99326238  2.73693605]
[ 4 45 39 72 74 44 30 17 60  2]
[ 4 45 39 72 74 44 30 17 60  2]
18
[[0.87912897 0.47282761]
 [0.0746979  0.28089229]
 [0.74249836 0.9394504 ]
 [0.40943269 0.18932336]
 [0.60718306 0.99129407]]


# 슬라이싱

In [14]:
#리스트
list = [ i for i in range( 10, 20 ) ]
print( list[0:5] )

r = [[ 1, 2, 3, 4, 5 ], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
print( r[2][2] )
print( r[:][:] )
print( r[2][:] )
print( r[1][:2])
print( r[:2][:2]) #앞이 행 뒥에가 열이 아님! 앞에 연산 이후 뒤 연산을 한다고 이해해야함!
#print( r[:,:] )  error


#Numpy
s = np.arange( 1, 16 ).reshape( 3, 5 )
print( s )
print( s[2][2] )
print( s[:][:] )
print( s[2][:] )
print( s[:2][:2] ) #앞이 행 뒤에가 열이 아님! 앞에 연산 이후 뒤 연산을 한다고 이해해야함!
print( s[:2, :2] ) #앞이 행 뒤에가 열이 맞음!
print( s[:, :] )
print( s[:-1, :-1] )
print( s[::-1,::-1] )

print( s[[0,2]] ) #0행과 2행을 꺼내라

[10, 11, 12, 13, 14]
13
[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
[11, 12, 13, 14, 15]
[6, 7]
[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
13
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[11 12 13 14 15]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1 2]
 [6 7]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[1 2 3 4]
 [6 7 8 9]]
[[15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]
[[ 1  2  3  4  5]
 [11 12 13 14 15]]


# 전치 행렬

In [16]:
print( s )                 #3행 5열
print ( s.T )              #4행 3열

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


# 결합 / 분리

In [18]:
a = [1, 2, 3]
b = [4, 5, 6]
for ab in zip(a, b):
    print( ab )

(1, 4)
(2, 5)
(3, 6)


In [42]:
e = np.floor( np.random.rand( 2, 15 ) * 100 )
print( e )
print ( np.hsplit( e, 3 ) ) #3개로 자르기
for arr in np.hsplit( e, 3 ) :
    print( arr )
for arr in np.hsplit( e, (3, 7, 12) ) :
    print( arr )

[[95. 61. 64. 20. 81. 71. 96. 10.  5. 21. 90. 97. 77. 72.  4.]
 [61. 18. 77. 80. 60. 84. 44. 71. 66. 33. 64. 53.  9. 32. 21.]]
[array([[95., 61., 64., 20., 81.],
       [61., 18., 77., 80., 60.]]), array([[71., 96., 10.,  5., 21.],
       [84., 44., 71., 66., 33.]]), array([[90., 97., 77., 72.,  4.],
       [64., 53.,  9., 32., 21.]])]
[[95. 61. 64. 20. 81.]
 [61. 18. 77. 80. 60.]]
[[71. 96. 10.  5. 21.]
 [84. 44. 71. 66. 33.]]
[[90. 97. 77. 72.  4.]
 [64. 53.  9. 32. 21.]]
[[95. 61. 64.]
 [61. 18. 77.]]
[[20. 81. 71. 96.]
 [80. 60. 84. 44.]]
[[10.  5. 21. 90. 97.]
 [71. 66. 33. 64. 53.]]
[[77. 72.  4.]
 [ 9. 32. 21.]]


In [56]:
f = np.array( [ 1, 2, 3, 4, 5 ] )
g = np.array( [ 'A', 'B', 'C', 'D', 'E' ] )
h = np.array( [ True, True, False, False, True ] )
# 삼항 연산                    조건 ? 참 : 거짓
#                             참 if 조건 else 거짓
print( [ x if z else y for x, y, z in zip( f, g, h ) ] )  # z가 참이면 x, 거짓이면 y를 리스트로 출력해라
print( np.where( h, f, g) )                               #.where(조간, 참일 때 값, 거짓일 때 값)
print( np.where( f < 3, '작다', '크다' ) )
print( np.where( h, '참', '거짓' ) )

[1, 2, 'C', 'D', 5]
['1' '2' 'C' 'D' '5']
['작다' '작다' '크다' '크다' '크다']
['참' '참' '거짓' '거짓' '참']


# 파일에 들어갔다가 나오기~

In [69]:
i = np.arange( 10 )
np.save( 'i.npy', i ) # 파일 i를 'i.npy'로 저장
ii = np.load( 'i.npy' )
print( ii )
print( type( ii ) )

j = np.arange( 10 )
k = np.arange( 10 )
np.savez( 'jk.npz', x=j, y=k )
jk = np.load( 'jk.npz' )
print( type( jk ) )
print( jk['x'] )
print( jk['y'] )

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
<class 'numpy.lib.npyio.NpzFile'>
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
