# Numpy

머신러닝을 관리하기 위해 자바언어는 불편하니까 주로 파이썬을 이용해서 머신러닝
대량의 데이터를 다루기 위해서는 넘파이& 판다쓰를 다뤄야한다
 => 파이썬에서 다루는 기본 자료형보다 더 복잡한 것들을 다루기 위해 넘파이 &판다쓰라는 라이브러리를 다룬다
넘파이 - 2차원 데이터& 기본적인 인덱싱  판다쓰 - 데이터 베이스 테이블 형태의 데이터를 다룬다 & 좀 더 유연한 인덱싱 
판다쓰에서는 데이터를 그대로 읽어 올 수 있다 .  csv, txt등 (그러므로 엑셀이나 sql등으로 데이터 불러오기가 용이)

In [ ]:
# numpy
# numerical python
# 고성능 수치를 위한 라이브러리
# 벡터나 행렬 연산에 편리한 기능 제공
# 모든 원소는 같은 자료형만 가능

In [3]:
import numpy as np
a = np.arange( 15 ) #range랑 비슷하다고 생각하면 됨
print( a )
a = a.reshape( 3, 5 ) #차원 변경 (행, 열, order = 'F') # C 행부터 할당이 기본값, F 열부터 할당
print( a )
print( type( a ) )
print( a.shape ) #(행, 열)출력
print( a.dtype ) # 데이터 타입 출력
print( a.ndim ) #차원 출력
print( a. size )
# print( dir ( np ) )

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
<class 'numpy.ndarray'>
(3, 5)
int32
2
15


In [9]:
b = [-1, -3, 5, 9, 12, 16, 99, 0, 8, 43] #list로 numpy 만듦 (호환됨)
print( b )
print( type( b ) )
b = np.array( b )
print( type( b ) )

t = ( 10, 20, 30, 40, 50 ) #tuple도 호환됨
print( type( t ) )
t = np.array( t )
print( type ( t ) )

s = { 10, 20, 30, 40, 50 } #set도 호환됨
print( type ( s ) )
s = np.array( s )
print( type( s ) )

[-1, -3, 5, 9, 12, 16, 99, 0, 8, 43]
<class 'list'>
<class 'numpy.ndarray'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'set'>
<class 'numpy.ndarray'>


In [27]:
print( b.shape )
print( b.ndim )
print( b.dtype )
print( b )

# print( help( np ) )
print( np.abs( b ) ) # 절대값
print( np.sqrt( np.abs( b ) ) ) # 제곱근
print( np.square( b ) ) # 제곱
print( np.isnan( b ) ) # NaN 여부
print( np.sum( b ) ) # 합계
print( np.mean( b ) ) # 평균
print( np.max( b ) )  # 최댓값
print( np.min( b ) ) # 최솟값
print( np.argmax( b ) ) #최댓값 인덱스
print( np.argmin( b ) ) #최솟값 인덱스
print( np.sort( b ) ) #정렬 오름차순
print( np.sort( b )[::-1] ) #정렬 내림차순 [ start: end : step ]

(10,)
1
int32
[-1 -3  5  9 12 16 99  0  8 43]
[ 1  3  5  9 12 16 99  0  8 43]
[1.         1.73205081 2.23606798 3.         3.46410162 4.
 9.94987437 0.         2.82842712 6.55743852]
[   1    9   25   81  144  256 9801    0   64 1849]
[False False False False False False False False False False]
188
18.8
99
-3
6
1
[-3 -1  0  5  8  9 12 16 43 99]
[99 43 16 12  9  8  5  0 -1 -3]
