# Pandas

In [2]:
# Series              1차원
# Dataframe           2차원 이상

In [3]:
import pandas as pd
import numpy as np

## Series

In [5]:
s = pd.Series( [ 1, 2, 3, 4, 5, 6, 7, 8, 9 ] )
print( type( s ) )
print( s. index )
print( s.dtype )
print( s )

s.index = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I' ]
print( s )

<class 'pandas.core.series.Series'>
RangeIndex(start=0, stop=9, step=1)
int64
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64
A    1
B    2
C    3
D    4
E    5
F    6
G    7
H    8
I    9
dtype: int64


In [6]:
s = pd.Series( [ 1, 2, 3, 4, 5, 6, 7, 8, 9 ], ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I' ]  )
print( s )
print( s.index )
print( s.values )
print( s[ 0 ] )
# 꺼내지긴 하지만, 우리가 인덱스를 지정했기 때문에
# series의 첫번째 데이터를 꺼내려면 우리가 지정한 인덱스를 입력하는게 좋음!
print( s[ 'A' ] )
print( s.A )
print( s[0:5] )
print( s['A':'D'] )

A    1
B    2
C    3
D    4
E    5
F    6
G    7
H    8
I    9
dtype: int64
Index(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'], dtype='object')
[1 2 3 4 5 6 7 8 9]
1
1
1
A    1
B    2
C    3
D    4
E    5
dtype: int64
A    1
B    2
C    3
D    4
dtype: int64


C:\Users\sc051\AppData\Local\Temp\ipykernel_34336\3867536465.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print( s[ 0 ] )


## Dictionary (Map, JSON) -> Series

In [8]:
d = { 'A':10, 'D':20, 'F':30, 'H':40 }
print( type( d ) )
for key, value in d.items() :
    print( key, ":", value )
print( d['A'] )
#print( d.A )         에러 (시리즈에서는 됨)

#print( d[0:3] )      에러 (딕셔너리는 슬라이싱이 안됨)
#print( d['A':'F'] )  에러 (딕셔너리는 슬라이싱이 안됨)

s = pd.Series( d )
print( s.index )
print( s.values )
print( s[ 'A' ])
print( s.A )
print( s[0:3] )
print( s['A':'F'] )

<class 'dict'>
A : 10
D : 20
F : 30
H : 40
10
Index(['A', 'D', 'F', 'H'], dtype='object')
[10 20 30 40]
10
10
A    10
D    20
F    30
dtype: int64
A    10
D    20
F    30
dtype: int64


## DataFrame

## Dictionary -> DataFrame

In [11]:
d = {
    'name' : [ '길은조', '양지우', '최이준', '한성경' ],
    'age' : [ '23', '21', '22', '21' ],
    'tel' : [ '1111-2222', '2222-3333', '3333-1111', '2222-3333']
}
print( type ( d ) )

df = pd.DataFrame( d )
print( df )
print( df.index )
print( df.columns )
print( df. values )
print('\n')
df.index.name = 'Num'
df.columns.name = 'User'
print( df )
print( df.index )
print( df.columns )
print( df.values )

<class 'dict'>
  name age        tel
0  길은조  23  1111-2222
1  양지우  21  2222-3333
2  최이준  22  3333-1111
3  한성경  21  2222-3333
RangeIndex(start=0, stop=4, step=1)
Index(['name', 'age', 'tel'], dtype='object')
[['길은조' '23' '1111-2222']
 ['양지우' '21' '2222-3333']
 ['최이준' '22' '3333-1111']
 ['한성경' '21' '2222-3333']]


User name age        tel
Num                     
0     길은조  23  1111-2222
1     양지우  21  2222-3333
2     최이준  22  3333-1111
3     한성경  21  2222-3333
RangeIndex(start=0, stop=4, step=1, name='Num')
Index(['name', 'age', 'tel'], dtype='object', name='User')
[['길은조' '23' '1111-2222']
 ['양지우' '21' '2222-3333']
 ['최이준' '22' '3333-1111']
 ['한성경' '21' '2222-3333']]


## Numpy -> DataFrame

In [13]:
n = np.array(
    [['길은조', 23, '1111-2222'],
     ['양지우', 21, '2222-3333'],
     ['최이준', 22, '3333-1111'],
     ['한성경', 21, '1111-3333']]
)
print( type( n ) )
df = pd.DataFrame( n )

df.columns = [ 'name', 'age', 'tel' ]
df.index = [ 'A', 'B', 'C', 'D' ]

print( df )
print( df.index )
print( df.columns )

print('\n')

df_1 = pd.DataFrame( n, columns=[ 'name', 'age', 'tel' ], index = ['A', 'B', 'C', 'D' ] )
print( df_1 )

print('\n')

print( df_1.describe()) #unique 종류

<class 'numpy.ndarray'>
  name age        tel
A  길은조  23  1111-2222
B  양지우  21  2222-3333
C  최이준  22  3333-1111
D  한성경  21  1111-3333
Index(['A', 'B', 'C', 'D'], dtype='object')
Index(['name', 'age', 'tel'], dtype='object')


  name age        tel
A  길은조  23  1111-2222
B  양지우  21  2222-3333
C  최이준  22  3333-1111
D  한성경  21  1111-3333


       name age        tel
count     4   4          4
unique    4   3          4
top     길은조  21  1111-2222
freq      1   2          1


In [14]:
print( df['name'] )
print( df[['name','tel']] ) #꺼내고 싶은 게 2차원일 때에는 대괄호 2개!
#print( df['name'][2] ) #되긴 하지만 우리가 붙여놓은 index가 있기 때문에 FutureWarning이 뜸
print( df['name']['C'] )
print( df['name'].C )
print( df['name']['B':'D'] )

print( df.name, df.age )
print( df.name.B )

A    길은조
B    양지우
C    최이준
D    한성경
Name: name, dtype: object
  name        tel
A  길은조  1111-2222
B  양지우  2222-3333
C  최이준  3333-1111
D  한성경  1111-3333
최이준
최이준
B    양지우
C    최이준
D    한성경
Name: name, dtype: object
A    길은조
B    양지우
C    최이준
D    한성경
Name: name, dtype: object A    23
B    21
C    22
D    21
Name: age, dtype: object
양지우


In [15]:
print( df[:][:] )
print( df[:2][:1] )
print( df[['name','tel']] )
# print( df[[ 0,2 ] )              #에러 컬럼명이 있는 경우 숫자 X
# print( df[0][0] )                #에러

  name age        tel
A  길은조  23  1111-2222
B  양지우  21  2222-3333
C  최이준  22  3333-1111
D  한성경  21  1111-3333
  name age        tel
A  길은조  23  1111-2222
  name        tel
A  길은조  1111-2222
B  양지우  2222-3333
C  최이준  3333-1111
D  한성경  1111-3333


In [16]:
df[ 'address' ] = [ '인천', '고양', '서울', '서울' ]          #column 추가
df['age'] = df['age'].astype(int)
df[ '얼라' ] = df[ 'age' ] < 22 
print( df['age'].dtype )
print( df )

del( df[ '얼라' ] )

print( df )

int32
  name  age        tel address     얼라
A  길은조   23  1111-2222      인천  False
B  양지우   21  2222-3333      고양   True
C  최이준   22  3333-1111      서울  False
D  한성경   21  1111-3333      서울   True
  name  age        tel address
A  길은조   23  1111-2222      인천
B  양지우   21  2222-3333      고양
C  최이준   22  3333-1111      서울
D  한성경   21  1111-3333      서울


## Series 정렬

In [18]:
s = pd.Series( [10, 40, 50, 20, 70, 60 ], index = ['f', 'e', 'd', 'b', 'c', 'a' ] )
s = s.sort_index( ascending = False )     #ascending = True가 기본값
s = s.sort_values()
print( s )

f    10
b    20
e    40
d    50
a    60
c    70
dtype: int64


## DataFrame 정렬

In [36]:
df = pd.DataFrame( [[ 4, 5, 1, 2 ],
                    [ 20, 10, 30, 50 ],
                    [300, 400, 200, 1000]], index = [ 'c', 'a', 'b' ], columns = [ 'B', 'C', 'A', 'D'])

print( df )
print('\n')
df = df.sort_index()    #index 정렬
df = df.sort_index( axis = 0 ) #행끼리 정렬 (위와 동일함)
df = df.sort_index( axis = 1, ascending = False ) # column으로 정렬

df = df.sort_values( by = 'A', ascending = False ) #행끼리
df = df.sort_values( by = ['A', 'B'] )

df = df.sort_values( by='b', axis=1 ) #열끼리
print( df )

     B    C    A     D
c    4    5    1     2
a   20   10   30    50
b  300  400  200  1000


     A    B    C     D
c    1    4    5     2
a   30   20   10    50
b  200  300  400  1000


## 슬라이싱

In [40]:
# .iloc    정수 인덱스
# .loc     라벨 인덱스
# .ix      deprecated

### list

In [43]:
m = [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ]
print( m )
print( m[2][2] )
print( m[:][:] )
print( m[:2][:2] )
# print( m[:2, :2] )        에러

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
9
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1, 2, 3], [4, 5, 6]]


### Numpy

In [46]:
n = np.array( m )
print( n )
print( n[2][2] )
print( n[:][:] )
print( n[:2][:2] )
print( n[:2, :2] )

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]


### Pandas

In [49]:
df = pd.DataFrame( n )
print( df )
print( df[2][2] )
print( df[:][:] )
print( df[:2][:2] )
# print( df[:2, :2] )                  # 에러

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
9
   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
   0  1  2
0  1  2  3
1  4  5  6


## iloc 정수 인덱스

In [52]:
df = pd.DataFrame( np.arange( 1, 21 ).reshape( 5, 4 ), columns=['A', 'B', 'C', 'D'] )
print( df )

    A   B   C   D
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20


In [72]:
# print( df[2][2] )                # 에러
print( df['C'][2] )
print( df[['A', 'D']] )
# print( df['A' : 'C'] )           # 에러
# print( df[[ 'A' : 'C' ]] )       # 에러
print( df.iloc[2][2] )
print( df.iloc[2, 2] )
# print( df.iloc[2, 'C'])          # 에러
print( df.iloc[:2, :2] )
print( df.iloc[:3:2, :3:2] )
print( df.iloc[:2, :-1] )
print( df.iloc[::-1, ::-1] )

11
    A   D
0   1   4
1   5   8
2   9  12
3  13  16
4  17  20
11
11
   A  B
0  1  2
1  5  6
   A   C
0  1   3
2  9  11
   A  B  C
0  1  2  3
1  5  6  7
    D   C   B   A
4  20  19  18  17
3  16  15  14  13
2  12  11  10   9
1   8   7   6   5
0   4   3   2   1


C:\Users\sc051\AppData\Local\Temp\ipykernel_34336\4225068184.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print( df.iloc[2][2] )


## loc 라벨 인덱스

In [75]:
print( df )
# print( df.loc[2, 2] )                 # 에러
print( df.loc[2, 'C'] )
# print( df.loc[:2, :2] )               # 에러
print( df.loc[:2, :'C'] )
print( df[:2] )
print( df.loc[1:3, 'B':'D'] )
print( df.loc[:, 'C'] )
print( df.loc[:, ['B', 'D']] )
print( df[['B' ,'D']] )

    A   B   C   D
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20
11
   A   B   C
0  1   2   3
1  5   6   7
2  9  10  11
   A  B  C  D
0  1  2  3  4
1  5  6  7  8
    B   C   D
1   6   7   8
2  10  11  12
3  14  15  16
0     3
1     7
2    11
3    15
4    19
Name: C, dtype: int32
    B   D
0   2   4
1   6   8
2  10  12
3  14  16
4  18  20
    B   D
0   2   4
1   6   8
2  10  12
3  14  16
4  18  20


In [79]:
df = pd.DataFrame( np.arange( 1, 21 ).reshape( 5, 4 ), columns=['A', 'B', 'C', 'D'] )
df['E'] = [ 31, 32, 33, 34, 35 ]
# df[5][:] = [ 90, 91, 92, 93, 94 ]               에러
# df.iloc[:, 5] = [ 40, 41, 42, 43, 44 ]          에러
# df.iloc[5, :] = [ 90, 91, 92, 93, 94 ]          에러
df.loc[5] = [ 90, 91, 92, 93, 94 ]
df.loc[:, 'F'] = [ 40, 41, 42, 43, 44, 45 ] 

df.loc[0, 'A'] = 99
df.loc[1, 'A':'C'] = [100, 101, 102]
df.loc[3, ['A', 'C', 'E']] = [200, 201, 202]

del( df['E'] )
# del( df.loc[:, 'F'] )               에러

# df.drop( 'F' )                      에러
df = df.drop( 'F', axis=1 )
# df.drop( 5, axis=1 )                에러
df = df.drop( 5 )
print( df )

     A    B    C   D
0   99    2    3   4
1  100  101  102   8
2    9   10   11  12
3  200   14  201  16
4   17   18   19  20


## Boolen Indexing

In [82]:
df = pd.DataFrame(
     [['kim', 20, '1111-2222'],
      ['lee', 30, '2222-1111'],
      ['park', 35, '3333-2222'],
      ['jung', 25, '3333-1111'],
      ['hong', 40, '1111-3333']], columns=[ 'name', 'age', 'tel']    
)
print( df )

print( df.loc[3, 'name'] )
print( df.loc[ df['age'] > 30, ['name', 'age' ]] )
print( df.loc[ df['name'] == 'kim', : ] )
print( df.loc[ ( df['age']>20 ) & ( df['age']<40 ), 'name':'tel'] )
print( df.loc[ [True, True, False, False, False], "name" ] )

   name  age        tel
0   kim   20  1111-2222
1   lee   30  2222-1111
2  park   35  3333-2222
3  jung   25  3333-1111
4  hong   40  1111-3333
jung
   name  age
2  park   35
4  hong   40
  name  age        tel
0  kim   20  1111-2222
   name  age        tel
1   lee   30  2222-1111
2  park   35  3333-2222
3  jung   25  3333-1111
0    kim
1    lee
Name: name, dtype: object


## 결측값 대체

In [85]:
df['address'] = [ '서울', np.nan, np.nan, '수원', None ]

print( df.loc[ df['address'] == np.nan, 'address' ]  )
print( df.loc[ df['address'] == None, 'address' ]  )
print( df.loc[ df['address'].isnull(), 'address' ] )

df.loc[ df['address'].isnull(), 'address' ] = '서울'

df.loc[ ::2, 'address' ] = '' 
df.loc[ df['address'] == '', 'address' ] = '서울' 
print( df )

Series([], Name: address, dtype: object)
Series([], Name: address, dtype: object)
1     NaN
2     NaN
4    None
Name: address, dtype: object
   name  age        tel address
0   kim   20  1111-2222      서울
1   lee   30  2222-1111      서울
2  park   35  3333-2222      서울
3  jung   25  3333-1111      수원
4  hong   40  1111-3333      서울


## 결측값 제거

In [88]:
df = pd.DataFrame(
     [['kim', 20, '1111-2222', '서울'],
      ['lee', 30, '2222-1111', np.nan ],
      ['park', 35, '3333-2222', '수원'],
      ['jung', 25, '3333-1111', np.nan],
      ['hong', 40, '1111-3333', np.nan]], columns=[ 'name', 'age', 'tel', 'address']    
)
df.loc[ 5, : ] = [ np.nan, np.nan, np.nan, np.nan ]

# df.dropna( how='all', inplace=True )
# df.dropna( how='any', inplace=True )

df['income'] = [ 300, np.nan, 400, 500, np.nan, 300 ]
# df['address'].fillna( value='서울', inplace=True )
df.fillna( {'address' : '서울'}, inplace=True ) 
df.fillna( {'income' : np.mean( df['income'] ) }, inplace=True )

df.drop( [4, 5], inplace=True )
df.drop( ['address', 'income'], axis=1, inplace=True )

print( df )

# print( df.T )
print( df.transpose() )              # 전치행렬

   name   age        tel
0   kim  20.0  1111-2222
1   lee  30.0  2222-1111
2  park  35.0  3333-2222
3  jung  25.0  3333-1111
              0          1          2          3
name        kim        lee       park       jung
age        20.0       30.0       35.0       25.0
tel   1111-2222  2222-1111  3333-2222  3333-1111


## Pandas 함수

In [91]:
df = pd.DataFrame( 
    [[ 'kim', 90, 80, 70 ],
     [ 'lee', 45, np.nan, 55 ],
     [ 'park', 76, 77, 83 ],
     [ 'hong', np.nan, np.nan, 77 ],
     [ 'kang', 35, 58, 52 ],
     [ 'jang', np.nan, np.nan, np.nan]], columns=[ 'name', 'kor', 'eng', 'mat' ]
)
print( df )

# print( df.count() )
# print( df.count( axis=1 ) )
# print( df.min() )
# print( df.loc[:, 'kor':'mat'].min( axis=1 ) )
# print( df.max() )
# print( df.loc[:, 'kor':'mat'].mean() )
# print( df.loc[:, 'kor':'mat'].mean( axis=1 ) )
# print( df.sum() )
# print( df.loc[:, 'kor':'mat'].sum( axis=1 ) )
# print( df.loc[:, 'kor':'mat'].median() )
# print( df.loc[:, 'kor':'mat'].cumsum() )
# print( df.loc[:, 'kor':'mat'].cumprod() )
# print( df.idxmax() )
# print( df.idxmin() )

# print( df.loc[:, 'kor':'mat'].var() )           # 분산
# print( df.loc[:, 'kor':'mat'].std() )           # 표준편차

df['tot'] = df.loc[:, 'kor':'mat'].sum( axis=1 )
df['avg'] = df.loc[:, 'kor':'mat'].mean( axis=1 )

print( df['kor'].corr( df['eng'] ) )
# 1          양의 상관관계
# 0          상관관계가 낮다
# -1         음의 상관관계

print( df )

   name   kor   eng   mat
0   kim  90.0  80.0  70.0
1   lee  45.0   NaN  55.0
2  park  76.0  77.0  83.0
3  hong   NaN   NaN  77.0
4  kang  35.0  58.0  52.0
5  jang   NaN   NaN   NaN
0.9926458576614517
   name   kor   eng   mat    tot        avg
0   kim  90.0  80.0  70.0  240.0  80.000000
1   lee  45.0   NaN  55.0  100.0  50.000000
2  park  76.0  77.0  83.0  236.0  78.666667
3  hong   NaN   NaN  77.0   77.0  77.000000
4  kang  35.0  58.0  52.0  145.0  48.333333
5  jang   NaN   NaN   NaN    0.0        NaN
